*&---------------------------------------------------------------------*
*& Include          ZR_GERAR_QUESTIONARIOS_SRC
*&---------------------------------------------------------------------*

SELECTION-SCREEN BEGIN OF BLOCK b1 WITH FRAME TITLE TEXT-001.
  PARAMETERS: p_materi TYPE string LOWER CASE,
              p_assunt TYPE string LOWER CASE,
              p_nivel  TYPE zde_quest_nivel,
              p_total  TYPE n LENGTH 2 AS LISTBOX VISIBLE LENGTH 10.

  PARAMETERS: p_qtdeOb TYPE n LENGTH 2 AS LISTBOX VISIBLE LENGTH 10,
              p_qtdeVf TYPE n LENGTH 2 AS LISTBOX VISIBLE LENGTH 10.

SELECTION-SCREEN END OF BLOCK b1.

SELECTION-SCREEN BEGIN OF LINE.
  SELECTION-SCREEN POSITION 10.
  SELECTION-SCREEN PUSHBUTTON (20) p_send USER-COMMAND send.

  SELECTION-SCREEN POSITION 35.
  SELECTION-SCREEN PUSHBUTTON (20) p_clear USER-COMMAND clear.
SELECTION-SCREEN END OF LINE.


SELECTION-SCREEN BEGIN OF SCREEN 3000.
SELECTION-SCREEN BEGIN OF BLOCK b2 WITH FRAME TITLE TEXT-002.
  SELECTION-SCREEN COMMENT /05(79) gv_qest1.
  SELECTION-SCREEN COMMENT /05(79) gv_qestc.

  " Opção 1
  SELECTION-SCREEN BEGIN OF LINE.
    SELECTION-SCREEN POSITION 5.
    PARAMETERS: p_op1 TYPE c RADIOBUTTON GROUP rb1.
    SELECTION-SCREEN POSITION 10.
    SELECTION-SCREEN COMMENT (70) gv_resp1.
  SELECTION-SCREEN END OF LINE.

  " Opção 2
  SELECTION-SCREEN BEGIN OF LINE.
    SELECTION-SCREEN POSITION 5.
    PARAMETERS: p_op2 TYPE c RADIOBUTTON GROUP rb1.
    SELECTION-SCREEN POSITION 10.
    SELECTION-SCREEN COMMENT (70) gv_resp2.
  SELECTION-SCREEN END OF LINE.

  " Opção 3
  SELECTION-SCREEN BEGIN OF LINE.
    SELECTION-SCREEN POSITION 5.
    PARAMETERS: p_op3 TYPE c RADIOBUTTON GROUP rb1.
    SELECTION-SCREEN POSITION 10.
    SELECTION-SCREEN COMMENT (70) gv_resp3.
  SELECTION-SCREEN END OF LINE.

  " Opção 4
  SELECTION-SCREEN BEGIN OF LINE.
    SELECTION-SCREEN POSITION 5.
    PARAMETERS: p_op4 TYPE c RADIOBUTTON GROUP rb1.
    SELECTION-SCREEN POSITION 10.
    SELECTION-SCREEN COMMENT (70) gv_resp4.
  SELECTION-SCREEN END OF LINE.

  " Botão de Responder
  SELECTION-SCREEN BEGIN OF LINE.
    SELECTION-SCREEN POSITION 30.
    SELECTION-SCREEN PUSHBUTTON (20) p_resp USER-COMMAND responde.
  SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN END OF BLOCK b2.

SELECTION-SCREEN END OF SCREEN 3000.

SELECTION-SCREEN BEGIN OF SCREEN 4000.
  SELECTION-SCREEN BEGIN OF BLOCK b3 WITH FRAME TITLE TEXT-002.
    SELECTION-SCREEN COMMENT /05(79) gv_qest2.
    SELECTION-SCREEN COMMENT /05(79) gv_qesta.

    "Verdadeiro
    SELECTION-SCREEN BEGIN OF LINE.
      SELECTION-SCREEN POSITION 5.
      PARAMETERS: p_opv TYPE c RADIOBUTTON GROUP rb2.
      SELECTION-SCREEN POSITION 10.
      SELECTION-SCREEN COMMENT (70) gv_respv.
    SELECTION-SCREEN END OF LINE.

    "Falso
    SELECTION-SCREEN BEGIN OF LINE.
      SELECTION-SCREEN POSITION 5.
      PARAMETERS: p_opf TYPE c RADIOBUTTON GROUP rb2.
      SELECTION-SCREEN POSITION 10.
      SELECTION-SCREEN COMMENT (70) gv_respf.
    SELECTION-SCREEN END OF LINE.

    SELECTION-SCREEN BEGIN OF LINE.
      SELECTION-SCREEN POSITION 30.
      SELECTION-SCREEN PUSHBUTTON (20) p_resp2 USER-COMMAND responde2.
    SELECTION-SCREEN END OF LINE.

  SELECTION-SCREEN END OF BLOCK b3.

SELECTION-SCREEN END OF SCREEN 4000.